# Generated by Django 5.2.12 on 2026-03-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('yfinance', 'yfinance'), ('ccxt', 'ccxt'), ('twelvedata', 'TwelveData'), ('journal_csv', 'Journal CSV')], max_length=20)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_inserted', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'symbol', 'timeframe'], name='market_inge_source_2b1f7d_idx'), models.Index(fields=['status', 'started_at'], name='market_inge_status_24f9cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('yfinance', 'yfinance'), ('ccxt', 'ccxt'), ('twelvedata', 'TwelveData'), ('journal_csv', 'Journal CSV')], max_length=20)),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(default='1h', max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_bars', to='market_ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'timestamp'], name='market_inge_symbol_47649e_idx'), models.Index(fields=['source', 'symbol', 'timestamp'], name='market_inge_source_ddbe92_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'symbol', 'timeframe', 'timestamp'), name='unique_marketbar_per_source_symbol_timeframe_timestamp')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('timeframe', models.CharField(default='1h', max_length=16)),
                ('snapshot_time', models.DateTimeField()),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('return_1d', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('return_7d', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('volatility_14d', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_fast', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_slow', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('crossover_signal', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_snapshots', to='market_ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', 'snapshot_time'], name='market_inge_symbol_09c4a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'timeframe', 'snapshot_time'), name='unique_metricsnapshot_per_symbol_timeframe_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(blank=True, default='', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('source_file', models.CharField(default='trading-journal.csv', max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('raw_row', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='market_ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
                'indexes': [models.Index(fields=['symbol', 'opened_at'], name='market_inge_symbol_461e0f_idx'), models.Index(fields=['source_file', 'row_number'], name='market_inge_source__2ddb6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_file', 'row_number'), name='unique_tradejournalentry_per_file_row')],
            },
        ),
    ]
